{
 "title": "Energy Forecast",
 "tags": [ "QA" ],
 "time": { "from": "now/d", "to": "now+16d" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Energy Forecast - ECMWF",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"timezone\"\n\n// option location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"Fronius\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast\" and r[\"_field\"] == \"ssrd\")\n  |> aggregateWindow(every: 1d, offset: -1m, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Energy Forecast - GFS",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "import \"timezone\"\n\n// option location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"Fronius\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast\" and r[\"_field\"] == \"dswrf\")\n  |> aggregateWindow(every: 1d, offset: -1m, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Energy Forecast - open-meteo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "import \"timezone\"\n\n// option location = timezone.location(name: \"Europe/Berlin\")\n// option location = timezone.location(name: \"Europe/Berlin\")\n\n\nfrom(bucket: \"Fronius\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast\" and r[\"_field\"] == \"forecast\")\n  |> aggregateWindow(every: 1d, offset: -1m, fn: sum)\n"
    }
   ]
  }
 ]
}