services:
################################################################################
# Fronius database influxDB 2.7
################################################################################
  influx_fronius:
    logging:
      options:
        max-size: "20m"
        max-file: "3"
        mode: "non-blocking"
    image: "influxdb:2.7"
    container_name: &database-container-name influx_fronius
    networks:
      fronius_net:
    volumes:
    # :ro leads to permission problems:
      - ./data/influxdb2/etc/influxdb:/etc/influxdb2
      - ./data/influxdb2/var/lib/influxdb:/var/lib/influxdb2
      - ./data/influxdb2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    env_file:
      - influxdb2.env
    secrets:
      - influxdb_init_password
    ports:
      - "8087:8086"
    entrypoint: ['bash', '-c', 'export DOCKER_INFLUXDB_INIT_PASSWORD=$$(cat /var/run/secrets/influxdb_init_password) ; source /entrypoint.sh']
#    user: "${USER_ID}"

################################################################################
# Fronius Grafana Dashboard
################################################################################
  grafana_fronius:
    logging:
      options:
        max-size: "20m"
        max-file: "3"
        mode: "non-blocking"
    image: "grafana/grafana"
    container_name: grafana_fronius
    # ToDo test plugin installation
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks:
      fronius_net:
    ports:
      - "3001:3000"
# for testing on host
#    network_mode: host
    volumes:
      - ./data/grafana/etc/grafana:/etc/grafana
      - ./data/grafana/var/lib/grafana:/var/lib/grafana
    restart: unless-stopped
    secrets:
      - influxdb_token_read
    user: "1000"
    entrypoint: ['bash', '-c', 'export INFLUXDB_TOKEN_READ=$$(cat /var/run/secrets/influxdb_token_read) ; source /run.sh']

################################################################################
# Fronius Web Rest API Readout
################################################################################
  fronius2influx:
    logging:
      options:
        max-size: "20m"
        max-file: "3"
        mode: "non-blocking"
    build:
      context: ..
      dockerfile: ./docker/application/Dockerfile
    image: 'fronius2influx:0.1'
    container_name: "fronius2influx"
    networks:
      fronius_net:
    restart: unless-stopped
    secrets:
      - influxdb_token_write
      - wallbox_token
    depends_on:
      - influx_fronius
    environment:
      INFLUXDB_HOST: *database-container-name
    env_file:
      - fronius2influx.env
    # Test: Fronius endpoints
    ports:
      - "5001:5000"

################################################################################
# ECMWF weather forecast testing cron in slim-python
################################################################################
  forecast2influx:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"
    build:
      context: ..
      dockerfile: ./docker/application/Dockerfile_forecast
    image: "forecast:0.3"
    container_name: forecast2influx
#    volumes:
#      - ../src/data:/ecmwf/src/data
    networks:
      fronius_net:
    restart: unless-stopped
    secrets:
      - influxdb_token_write
    depends_on:
      - influx_fronius
    environment:
      INFLUXDB_HOST: *database-container-name
    env_file:
      - fronius2influx.env

secrets:
    influxdb_init_password:
        file: data/secrets/influxdb_init_password
    influxdb_token_write:
        file: data/secrets/influxdb_token_write
    influxdb_token_read:
        file: data/secrets/influxdb_token_read
    wallbox_token:
        file: data/secrets/wallbox_token

networks:
    fronius_net:
        driver: bridge