FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install cron
RUN pip install --upgrade pip

# in case pygrib fails with a future v>2.1.6, we got a fallback here
#RUN apt-get install -y  \
#    gcc  \
#    libeccodes-dev
#RUN pip install Cython packaging pyproj
#
#COPY src/pygrib-2.1.6 /app/src/pygrib
#WORKDIR /app/src/pygrib
#RUN ECCODES_DIR=/usr/include/x86_64-linux-gnu python setup.py install && \
#    rm -rf /app/src/pygrib

WORKDIR /app/

# requirements
COPY src/requirements_forecast.txt /app/src/requirements_forecast.txt
RUN pip install -r /app/src/requirements_forecast.txt && \
    rm -f /app/requirements_forecast.txt

# cleansing
RUN apt-get -y autoremove && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# common modules
COPY src/sun_influx.py /app/src/
COPY src/fronius_aux.py /app/src/
# application ECMWF
COPY src/ecmwf_download.py /app/src/
# application GFS
COPY src/gfs_fc_*.py /app/src/
# application open-meteo
COPY src/open-meteo2influx.py /app/src/
# data
COPY src/data/parameter.json /app/src/data/

# Copy and enable your CRON task + copy appropriate shells for environment vars
COPY docker/cron/*.sh /app/
RUN chmod +x /app/*.sh
COPY docker/cron/cron /etc/cron.d/cron
RUN chmod 0644 /etc/cron.d/cron
RUN crontab /etc/cron.d/cron
# Create empty log (TAIL needs this)
RUN touch /var/log/cron.log

ENV PYTHONPATH=/app/
# CMD ["cron", "&&", "tail", "-f", "/var/cron.log"]
# http://web.archive.org/web/20230118040109/https://roboslang.blog/post/2017-12-06-cron-docker/
CMD ["/app/start.sh"]