FROM python:3.12-slim

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install cron

WORKDIR /app/

# pre-requirement for pygrib: this is required with containers only on a
# raspberry, however, it consumes additional 300 MB of disk space
RUN apt-get -y install python3-grib

# requirements
COPY src/requirements_forecast.txt /app/src/requirements_forecast.txt
RUN apt-get -y install --upgrade pip && \
    pip install -r /app/src/requirements_forecast.txt && \
    rm -f /app/requirements_forecast.txt

# common modules
COPY src/sun_influx.py /app/src/
COPY src/fronius_aux.py /app/src/
# application ECMWF
COPY src/ecmwf_download.py /app/src/
# application GFS
COPY src/gfs_fc_*.py /app/src/
# data
COPY src/data/parameter.json /app/src/data/

# Copy and enable your CRON task + copy appropriate shells for environment vars
COPY docker/cron/*.sh /app/
RUN chmod +x /app/*.sh
COPY docker/cron/cron /etc/cron.d/cron
RUN chmod 0644 /etc/cron.d/cron
RUN crontab /etc/cron.d/cron
# Create empty log (TAIL needs this)
RUN touch /var/log/cron.log

ENV PYTHONPATH=.
# CMD ["cron", "&&", "tail", "-f", "/var/cron.log"]
# http://web.archive.org/web/20230118040109/https://roboslang.blog/post/2017-12-06-cron-docker/
CMD /app/start.sh